#!/usr/bin/env bash

# No effing idea why these can't live in .zshrc

autoload bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
complete -C '/usr/local/bin/aws_completer' aws